---
- name: Update package cache (Ubuntu)
  ansible.builtin.apt:
    name: aptitude
    state: present
    update_cache: true
  when: ansible_distribution == "Debian"

- name: Update package cache (Amazon Linux)
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_cache: true
  when: ansible_distribution  == 'RedHat'

- name: Install dependencies (Ubuntu)
  ansible.builtin.package:
    name:
      - net-tools
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - gnupg-agent
      - autoconf
      - dpkg-dev
      - file
      - g++
      - gcc
      - libc-dev
      - make
      - pkg-config
      - re2c
      - wget
      - neovim
      - git
      - golang-go
    state: present
    update_cache: true
  when: ansible_distribution == "Debian"

- name: Install dependencies (Amazon Linux)
  ansible.builtin.yum:
    name:
      - gcc-c++
      - gcc
      - glibc-devel
      - make
      - pkgconfig
      - golang
    state: present
    update_cache: true
  when: ansible_distribution == 'RedHat'
